DROP TABLE if EXISTS STUDENTS_COURSES,
                     STUDENTS,
                     COURSES,
                     GROUPS CASCADE;
CREATE TABLE GROUPS
(
    id SERIAL PRIMARY KEY NOT NULL UNIQUE,
	name CHARACTER VARYING(255)
);
CREATE TABLE STUDENTS
(
    id SERIAL PRIMARY KEY NOT NULL UNIQUE,
	first_name CHARACTER VARYING(255) NOT NULL,
	last_name CHARACTER VARYING(255) NOT NULL,
	group_id INTEGER,
	FOREIGN KEY (group_id)  REFERENCES GROUPS (id) ON DELETE CASCADE
);
CREATE TABLE COURSES
(
    id INTEGER UNIQUE,
	name CHARACTER VARYING(255) PRIMARY KEY,
	description CHARACTER VARYING(255)
);

CREATE TABLE STUDENTS_COURSES
(
    student_id INTEGER REFERENCES STUDENTS(id) ON DELETE CASCADE,
    course_name CHARACTER VARYING(255) REFERENCES COURSES(name) ON DELETE CASCADE
);



